name = "ed-alfie-winmax-advisory"
main = "dist/server.cjs"
compatibility_date = "2026-06-12"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
DISABLE_HMR = "true"
